### ISSUE TITLE
Content from conf18 missing

### ISSUE THREAD

**Issue by ghost** [rkovar/splunk-hunting-helpers#2]
Greetings sir, 

It seems that the content from the conf18 cloud talk is missing from the appropriate folder. 

Didn't know if you were aware and wanted to give you a heads up.

**Comment by nbheu1** [comment]
Hey. I am also waiting for this content. Great session @conf18 by the way.

**Comment by ghost** [comment]
Agree !

**Comment by rkovar** [comment]
@iostreamz @nbheu1 I just uploaded the "searches" to the msft cloud section. I'm having some... issues with internal stuff but full preso will be released shortly. @sbrant is gonna put the phantom stuff up there soon!
